/* Shared template renderer, built for the personal web app. */
const cache={},screen=document.getElementById('screen');let current,definition,stack=[],renderTimer,editingField=null,compositionRenderPending=false;
const browserInput=requireModule('services/browser-input.js');
function resolve(base,target){const parts=(target.startsWith('.')?base.slice(0,base.lastIndexOf('/')+1)+target:target).split('/'),out=[];for(const p of parts){if(p==='..')out.pop();else if(p&&p!=='.')out.push(p);}return out.join('/')+(target.endsWith('.js')?'':'.js');}
function requireModule(name){if(cache[name])return cache[name].exports;const module={exports:{}};cache[name]=module;if(!modules[name])throw new Error('Missing module '+name);modules[name](s=>requireModule(resolve(name,s)),module,module.exports);return module.exports;}
window.Page=d=>{definition=d;};window.App=()=>{};
window.wx={getStorageSync:k=>{try{return JSON.parse(localStorage.getItem(k))||undefined;}catch{return undefined;}},setStorageSync:(k,v)=>localStorage.setItem(k,JSON.stringify(v)),removeStorageSync:k=>localStorage.removeItem(k),showToast:({title})=>{const t=document.getElementById('toast');t.textContent=title;t.style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.style.display='none',2800);},showModal:({title,content,success,showCancel=true})=>{const overlay=document.createElement('div');overlay.className='modal-overlay';const box=document.createElement('section');box.className='modal-box';box.setAttribute('role','dialog');const heading=document.createElement('h3');heading.textContent=title;const copy=document.createElement('p');copy.textContent=content;box.append(heading,copy);const actions=document.createElement('div');actions.className='modal-actions';function choice(label,yes){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{overlay.remove();success&&success({confirm:yes,cancel:!yes});};actions.appendChild(b);}if(showCancel)choice('取消',false);choice('确定',true);box.append(actions);overlay.append(box);(document.querySelector('dialog[open]')||document.body).append(overlay);},navigateTo:({url})=>navigate(url,'push'),redirectTo:({url})=>navigate(url,'replace'),switchTab:({url})=>navigate(url,'tab'),navigateBack:()=>{const prev=stack.pop();if(prev){current=prev;render();current.onShow&&current.onShow();}else navigate('/pages/home/home','tab');},setClipboardData:({data})=>{navigator.clipboard.writeText(data).then(()=>wx.showToast({title:'已复制'}));},env:{USER_DATA_PATH:'preview'},getFileSystemManager:()=>({writeFile:({data,success})=>{window.exportData=data;success();}}),shareFileMessage:async()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([window.exportData],{type:'application/json'}));a.download='课课记账本备份.json';a.click();},cloud:{init(){},callFunction(){return Promise.reject(new Error('Cloud unavailable in local preview'));}}};
const evaluate=requireModule('web/template.js').evaluate;
function val(s,scope){if(s===null)return null;const m=s.match(/^{{([^{}]*)}}$/);if(m)return evaluate(m[1],scope);return s.replace(/{{([\s\S]*?)}}/g,(_,e)=>{const v=evaluate(e,scope);return v==null?'':String(v);});}
function nodes(parent,scope){const frag=document.createDocumentFragment();let chain=false,taken=false;for(const n of parent.childNodes){if(n.nodeType===3){frag.appendChild(document.createTextNode(val(n.textContent,scope)??''));continue;}if(n.nodeType!==1)continue;if(n.hasAttribute('wx:if')){chain=true;taken=!!val(n.getAttribute('wx:if'),scope);if(!taken&&!n.hasAttribute('wx:for'))continue;}else if(n.hasAttribute('wx:elif')){if(!chain||taken)continue;taken=!!val(n.getAttribute('wx:elif'),scope);if(!taken)continue;}else if(n.hasAttribute('wx:else')){if(!chain||taken)continue;taken=true;}else{chain=false;taken=false;}frag.appendChild(element(n,scope));}return frag;}
function element(n,scope,loop=false){if(n.hasAttribute('wx:for')&&!loop){const list=val(n.getAttribute('wx:for'),scope)||[],f=document.createDocumentFragment();list.forEach((item,index)=>{f.appendChild(element(n,{...scope,[n.getAttribute('wx:for-item')||'item']:item,[n.getAttribute('wx:for-index')||'index']:index},true));});return f;}if(n.hasAttribute('wx:if')&&!val(n.getAttribute('wx:if'),scope))return document.createDocumentFragment();const tag=n.tagName;const el=document.createElement(tag==='text'?'span':tag==='button'?'button':tag==='input'?'input':tag==='textarea'?'textarea':tag==='switch'?'input':'div');el.className=tag==='text'?'wx-text':tag==='block'?'wx-block':'';
for(const a of n.attributes){if(a.name.startsWith('wx:')||a.name.startsWith('bind')||a.name.startsWith('catch'))continue;const value=val(a.value,scope);if(a.name==='class'){el.className+=' '+(value||'');continue;}if(['disabled','checked'].includes(a.name)){el[a.name]=!!value;continue;}if(a.name==='value'){el.value=value==null?'':value;continue;}if(a.name==='style'){el.style.cssText=String(value||'').replace(/([\d.]+)rpx/g,'calc($1 * var(--rpx))');continue;}if(a.name==='type'&&(tag==='input')){browserInput.configure(el,value);continue;}if(!['range','range-key','mode','loading','open-type'].includes(a.name))el.setAttribute(a.name,value==null?'':value);}
const call=(name,detail={})=>{if(!name)return;const owner=current;const handler=owner[name];if(handler){const r=handler.call(owner,{currentTarget:{dataset:{...el.dataset}},detail});if(r&&r.catch)r.catch(e=>{console.error(e);wx.showToast({title:e.message});});}};
if(n.hasAttribute('bindtap')||n.hasAttribute('catchtap')){el.tabIndex=0;el.setAttribute('role','button');el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();el.click();}});el.addEventListener('click',e=>{e.stopPropagation();call(n.getAttribute('bindtap')||n.getAttribute('catchtap'));});}
if(tag==='input'||tag==='textarea'){if(tag==='input')browserInput.configure(el,n.getAttribute('type')||'text');browserInput.bind(el,value=>{editingField=el.dataset.field;try{call(n.getAttribute('bindinput'),{value});}finally{editingField=null;}},()=>{if(compositionRenderPending){compositionRenderPending=false;render();}});el.addEventListener('change',()=>call(n.getAttribute('bindchange'),{value:el.value}));}
else if(tag==='switch'){el.type='checkbox';el.className+=' wx-switch';el.addEventListener('change',()=>call(n.getAttribute('bindchange'),{value:el.checked}));}
else if(tag==='picker'){el.className+=' wx-picker';el.appendChild(nodes(n,scope));const mode=n.getAttribute('mode'),v=val(n.getAttribute('value')||'',scope);let control;if(mode==='date'||mode==='time'){control=document.createElement('input');control.type=mode==='time'?'time':n.getAttribute('fields')==='month'?'month':'date';control.value=v||'';if(n.hasAttribute('end'))control.max=val(n.getAttribute('end'),scope);}else{control=document.createElement('select');const range=val(n.getAttribute('range')||'[]',scope)||[];range.forEach((r,i)=>{const o=document.createElement('option');o.value=i;o.textContent=n.getAttribute('range-key')?r[n.getAttribute('range-key')]:r;control.appendChild(o);});control.value=v||0;}control.addEventListener('change',()=>call(n.getAttribute('bindchange'),{value:control.value}));el.appendChild(control);}
else el.appendChild(nodes(n,scope));return el;}
function render(){if(!current)return;if(browserInput.isComposing()){compositionRenderPending=true;return;}clearTimeout(renderTimer);const prevScroll=screen.scrollTop,focused=screen.contains(document.activeElement)?document.activeElement:null,field=focused&&/^(INPUT|TEXTAREA)$/.test(focused.tagName)&&focused.dataset.field,selection=focused&&focused.selectionStart;const route=current.route;const xml='<root xmlns:wx="urn:wx">'+templates[route].replace(/wx:else(?=\s|>)/g,'wx:else=""').replace(/&(?!(amp|lt|gt|quot|apos);)/g,'&amp;')+'</root>';const doc=new DOMParser().parseFromString(xml,'application/xml');if(doc.querySelector('parsererror')){screen.textContent=doc.querySelector('parsererror').textContent;throw new Error(screen.textContent);}screen.replaceChildren(nodes(doc.documentElement,current.data));document.getElementById('page-style').textContent=(styles.app+'\n'+styles[route]).replace(/(^|\n)page\s*\{/g,'$1#screen{').replace(/([\d.]+)rpx/g,'calc($1 * var(--rpx))');screen.scrollTop=prevScroll;if(field){const target=screen.querySelector('[data-field="'+field+'"]');if(target){target.focus({preventScroll:true});if(selection!=null&&target.setSelectionRange)try{target.setSelectionRange(selection,selection);}catch{}}}const tab=appConfig.tabBar.list.find(t=>t.pagePath===route);document.getElementById('tabs').style.display=tab?'flex':'none';document.getElementById('back').style.visibility=tab?'hidden':'visible';document.getElementById('nav-title').textContent=tab?'课课记':({course:'课程小账本','course-form':'添加课程',renewal:'记录续费','record-form':'记一次上课',family:'家庭与共享','child-form':'宝贝小档案',join:'加入家庭'}[route.split('/')[1]]||'课课记');document.getElementById('tabs').innerHTML=appConfig.tabBar.list.map(t=>'<button class="'+(t.pagePath===route?'active':'')+'" data-route="'+t.pagePath+'"><img src="./'+(t.pagePath===route?t.selectedIconPath:t.iconPath)+'">'+t.text+'</button>').join('');for(const b of document.querySelectorAll('#tabs button'))b.onclick=()=>navigate('/'+b.dataset.route,'tab');window.webPage=current;}
async function navigate(url,mode){if(mode==='push'&&current)stack.push(current);if(mode==='tab')stack=[];const [pathname,search='']=url.split('?');const route=pathname.replace(/^\//,'');delete cache[route+'.js'];requireModule(route+'.js');const instance={...definition,data:JSON.parse(JSON.stringify(definition.data||{})),route,setData(patch){Object.assign(this.data,patch);if(editingField&&Object.keys(patch).every(k=>k===editingField))return;if(current===this){clearTimeout(renderTimer);renderTimer=setTimeout(render,0);}}};current=instance;screen.scrollTop=0;instance.onLoad&&instance.onLoad(Object.fromEntries(new URLSearchParams(search)));render();if(instance.onShow)await instance.onShow();render();}
document.getElementById('back').onclick=()=>wx.navigateBack();window.addEventListener('error',e=>console.error('Preview error:',e.message));window.startWeb=()=>navigate('/pages/home/home','tab');window.refreshLedger=()=>{if(current){current.loaded=false;current.onShow&&current.onShow();}};
